[workspace]
features_always_increment_minor = true

[changelog]
protect_breaking_commits = true
sort_commits = "newest"
trim = true

header = """# Changelog

## [Unreleased]
"""

body = """{% macro print_commit(commit) -%}
- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }} - ([{{ commit.id | truncate(length=7, end="") }}]({{ remote.link }}/commit/{{ commit.id }}))
{% endmacro -%}

{% if version %}
    {% if previous.version %}
        ## [{{ version }}]({{ release_link }})
    {% else %}
        ## [{{ version }}]
    {% endif %}
{% endif %}

{% for group, commits in commits
| filter(attribute="merge_commit", value=false)
| unique(attribute="message")
| group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}

    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor -%}
    {% for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor %}
"""

commit_parsers = [
	{ message = "^feat", group = "Added" },
	{ message = "^fix", group = "Fixed" },
	{ message = "^doc", group = "Documented" },
	{ message = "^perf", group = "Performance" },
	{ message = "^update", group = "Updated" },
	{ message = "^refactor", skip = true },
	{ message = "^style", skip = true },
	{ message = "^test", skip = true },
	{ message = "^chore\\(release\\)", skip = true },
	{ message = "[Pp]repare to release", skip = true },
	{ message = "^chore", skip = true },
	{ body = ".*security", group = "Security" },
	{ body = ".*[dD]eprecate.*", group = "Deprecated" },
]

link_parsers = [
	{ pattern = "[fF]ixes #(\\d+)", text = "fixes [#${1}]", href = "{{ remote.link }}/issues/$1" },
	{ pattern = "[cC]loses #(\\d+)", text = "closes [#${1}]", href = "{{ remote.link }}/issues/$1" },
	{ pattern = "[sS]ee #(\\d+)", text = "see [#${1}]", href = "{{ remote.link }}/issues/$1" },
	{ pattern = "#(\\d+)", href = "{{ remote.link }}/issues/$1" },
	{ pattern = "GH-(\\d+)", href = "{{ remote.link }}/issues/$1" },
	{ pattern = "PR-(\\d+)", href = "{{ remote.link }}/pull/$1" },
	{ pattern = "RFC(\\d+)", text = "ietf-rfc$1", href = "https://datatracker.ietf.org/doc/html/rfc$1" },
]
